### ISSUE TITLE
Lists do not fill the entire screen vertically

### ISSUE THREAD

**Issue by atifsyedali** [ankitgaurav/Perfect-New-Tab#3]
The lists should be able to fill the entire available vertical space for larger screens. That is, the lists should automatically take up the remaining vertical space, otherwise the list container is much smaller than can be thus requiring needless scrolling.

**Comment by theankitgaurav** [comment]
This is taken care of in 6b5ea20034c0cd2891804977555a5801fab39403.
Shall be publishing the new version will lot more features, tweaks and perf increments.

**Comment by iamdebojyoti** [comment]
Can I contribute to this issue
